# Generated by Django 4.1.7 on 2023-08-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_premier',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Примьера в мире'),
        ),
    ]
