# Generated by Django 4.1.7 on 2023-08-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_world_premier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='mail',
            new_name='email',
        ),
    ]
